spring.application.name=backend

app.google.script.url=${APP_GOOGLE_SCRIPT_URL:https://script.google.com/macros/s/AKfycbwm9cnb4zBV4OVgJT3t_FrX2mpNXrneCKfLZEarYu_Xf0Um9jwHHSmFPtXFu2z_BX6x/exec}
app.google.script.secret=${APP_GOOGLE_SCRIPT_SECRET:vervang-dit-door-een-lange-geheime-sleutel}

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:boxtheather}
spring.datasource.username=${DB_USERNAME:boxtheather}
spring.datasource.password=${DB_PASSWORD:boxtheather}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true

logging.level.root=INFO
logging.level.com.example.backend=INFO
