spring.application.name=backend

app.google.script.url=https://script.google.com/macros/s/AKfycbwm9cnb4zBV4OVgJT3t_FrX2mpNXrneCKfLZEarYu_Xf0Um9jwHHSmFPtXFu2z_BX6x/exec
app.google.script.secret=vervang-dit-door-een-lange-geheime-sleutel
logging.level.root=DEBUG
logging.level.com.example.backend=DEBUG
